# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 881100c28ccbc375f06f2b10a9e5230ed729f72e6df994dc39af66c295c849bcbd714d943b8dc8d42ba792243319da2c4a91b89606931d43ee496d684ee5d70d

test:
  secret_key_base: cf287794aa3085fd0cb81a1865fe160134979a09aee2c4884c50ced93f777b83ee0a2fd62e7913178d5adcefd8185518e9915ad96c1ad834f5974a6d902a3ee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
